language: node_js
node_js:
- 12
install:
- npm install
scripts:
- npm run build

deploy:
  provider: npm
  email: austin.cawley@gmail.com
  skip_cleanup: true
  api_key:
    secure: rjBagMN9riLhkUvYR+fFR7z06aaNf6qYO1Xh+VXg5RSyi5iGSDqv1bAF7deM9ztlAhmhl6yGs6S963OFk9ETuhuiYSsavTH2xFRKP0toQfx4mJCohbHKChUGK8WCT8r6YIMVWJEwgCLgB9DSC3PLFKdIuIGHu3FPHGK+QPRK1SFwsU8/9jCZV+eNJAz0YVw6TQTpZbByJEGAMWQOzPKe5t4NvA9SNvBSIbjJSeeS+ftwdO1XKv5e/UjT+pwVxxPokP8xb8K7N1bdfDJZQQSQPFHxtyIZilQaDo9UgVTC3llaZHagyw68uT52cMAtD4wAdJ0D61NDOJZPKWHKhtjiz/9YA7iEQSRlY5WcqIIv4hz/+z/J2eTC6iD0y6s/2IgwUptGxjm5NCikrUU8VuqPTFOwi/deFQlYorHdE3YDcLWf5Qljf3jzEpPBphXnCCNYLHcSg5Xd28SpJQ18QZ8lYJvBNPPkVFS3RXdMYco3lnzKXUQkGdI2atjtWw2ymDj0sbGGfCpcOkBYGjTLSJdChKZB6qewhaBcMaG4fVqtLiy8Il0PjFsi3Lr8z/pFaoKsvCvTFTYitlsXBvlP5E5j8rSrrre/0lhzaopC8saqlWIWahJrvlTtrWPZogoIFaX8nZug7MRBwLjXzaJsoxW0B4RccwZng/VeciKiKY4zDJU=
  on:
    tags: true
    branch: master
